# Generated by Django 5.0.3 on 2024-04-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("admin", "Admin")],
                default="",
                max_length=10,
            ),
        ),
    ]
