# Generated by Django 5.0.3 on 2024-04-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_customuser_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_type",
        ),
    ]
